name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
      - stable
  pull_request:
    branches:
      - master
      - main

jobs:
  check_base_image_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check for changes in BASE image
      id: check_base_changes
      run: echo "::set-output name=changed::$(if [ -n "$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep 'BASE_IMAGE')" ]; then echo true; else echo false; fi)"

  build:
    runs-on: ubuntu-latest
    needs: check_base_image_changes
    if: ${{ needs.check_base_image_changes.outputs.changed == 'false' }}

    steps:
    - uses: actions/checkout@v3

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          CURRENT_DATE=$(date +'%Y%m%d')
          CURRENT_DATE_WITH_HOUR=$(date +'%Y%m%d%H')
          IMAGE_NAME="ghcr.io/tna76874/podman-xampp"

          # Build image for master branch
          if [ ${{ github.ref }} == 'refs/heads/master' ] || [ ${{ github.ref }} == 'refs/heads/main' ]; then
            CHANNEL="latest"
          fi

          # Build image for stable branch
          if [ ${{ github.ref }} == 'refs/heads/stable' ]; then
            CHANNEL="stable"
            docker build . --file Dockerfile --tag ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}
            docker push ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE}
            docker build . --file Dockerfile --tag ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}
            docker push ${IMAGE_NAME}:${CHANNEL}-${CURRENT_DATE_WITH_HOUR}
          fi

          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${COMMIT_HASH}
          docker push ${IMAGE_NAME}:${COMMIT_HASH}

          docker build . --file Dockerfile --tag ${IMAGE_NAME}:${CHANNEL}
          docker push ${IMAGE_NAME}:${CHANNEL}